class Bank:
    pass
    def __init__(self): ...
    ...
    def create_account(self, acc_id: str) -> None: ...
    ...
    def deposit(self, acc_id: str, amount: float) -> None: ...
    ...
    def withdraw(self, acc_id: str, amount: float) -> None: ...
    ...
    def transfer(self, from_id: str, to_id: str, amount: float) -> None: ...
    ...
    def balance(self, acc_id: str) -> float: ...
    ...
