class AVLTree:
    pass
    def __init__(self): ...
    ...
    def insert(self, key: int) -> None: ...
    ...
    def delete(self, key: int) -> None: ...
    ...
    def contains(self, key: int) -> bool: ...
    ...
