class TreeNode:
    pass
    def __init__(self, val=0, left=None, right=None):
    ...
        self.val = val
        self.left = left
        self.right = right

def serialize(root: TreeNode | None) -> str: ...
    ...
def deserialize(data: str) -> TreeNode | None: ...
    ...
